"""Write ``reports/figures/FIGURE_MANIFEST.md`` from the provenance sidecars.

Usage: ``uv run python scripts/figures/build_figure_manifest.py``
"""

from __future__ import annotations

from virtual_cell.visualization import common
from virtual_cell.visualization.sources import EXTRACTORS

HEADER = """# Figure manifest

Provenance for every figure in `reports/figures/`, generated by
`scripts/figures/build_figure_manifest.py` from the sidecars in
`data/figure_sources/*.provenance.json`. Do not edit by hand.

Every figure is drawn **only** from its figure-source table, and every table is
extracted deterministically from frozen output artifacts (or, for Figure 7, the
Kaden diagnostic's own outputs) by `scripts/figures/extract_figure_sources.py`.
No plotted number is typed into a plotting script. `tests/test_figures.py`
re-extracts each table and requires byte-identical output.

Reproduce everything:

```bash
uv run python scripts/figures/extract_figure_sources.py
for f in scripts/figures/plot_*.py; do uv run python "$f"; done
uv run python scripts/figures/build_figure_manifest.py
```

Result story and suitability: [`README.md`](README.md).
"""


FIG10 = """
## 10_arc_submission_scorecard (not generated: no real score exists)

- figure: `reports/figures/10_arc_submission_scorecard.png`, `.svg`, **generated only
  after a real Arc score exists**
- figure script: `scripts/figures/plot_arc_submission_scorecard.py`
- input: `data/figure_sources/arc_submission_v1_scorecard.json`, filled by hand **only**
  from `vcc status <entry> --json` after scoring; schema
  `data/figure_sources/arc_submission_v1_scorecard.schema.json` (overall, six members,
  partition, panel, anchor set)
- reference marks: 0 (baseline) and 1 (replicate), plus the per-member control-emitting
  score read from the frozen `outputs/arc_bridge_v1/score_accounting.csv`
- without the input file the script draws nothing and exits 0; `load_scorecard` rejects
  missing fields and non-finite values, so no placeholder bar can be drawn
"""


def main() -> None:
    lines = [HEADER]
    for name in EXTRACTORS:
        prov_path = common.SOURCES_DIR / f"{name}.provenance.json"
        if not prov_path.exists():
            lines.append(f"\n## {name}\n\n*not generated*\n")
            continue
        p = common.load_provenance(name)
        head = p["git_head"]
        lines.append(f"\n## {name}\n")
        lines.append(f"- figure: `reports/figures/{name}.png`, `reports/figures/{name}.svg`")
        lines.append(f"- figure source: `{p['figure_source']}`")
        lines.append(f"- report: `{p['report']}`")
        lines.append(f"- extraction script: `{p['extraction_script']}`")
        lines.append(f"- figure script: `{p['figure_script']}`")
        lines.append(
            f"- generated: {p['generated']} at git HEAD `{head['commit'][:12]}`"
            + (" (uncommitted working tree)" if head["dirty"] else "")
        )
        lines.append("- source artifacts:")
        for s in p["source_files"]:
            fr = (
                ", ".join(f"`{f}`" for f in s["freezes"])
                or "**not in any freeze** (new diagnostic output)"
            )
            lines.append(f"  - `{s['path']}` — sha256 `{s['sha256'][:16]}…` — pinned by {fr}")
        if p.get("notes"):
            lines.append(f"- notes: {p['notes']}")
    lines.append(FIG10)
    (common.FIGURES_DIR / "FIGURE_MANIFEST.md").write_text("\n".join(lines) + "\n")
    print(f"  wrote {common.FIGURES_DIR / 'FIGURE_MANIFEST.md'}")


if __name__ == "__main__":
    main()
